<?php
	
function quran_node_info() {
	$content = array();
    $content['chapter']  = array (
	  'name' => 'Chapter',
	  'type' => 'chapter',
	  'description' => 'Chapters of the Holy Quran. 114 chapters in all',
	  'title_label' => 'Title',
	  'body_label' => 'Body',
	  'min_word_count' => '0',
	  'help' => '',
	  'node_options' => 
	  array (
		'status' => true,
		'promote' => true,
		'sticky' => false,
		'revision' => false,
	  ),
	  'old_type' => 'chapter',
	  'orig_type' => '',
	  'module' => 'node',
	  'custom' => '1',
	  'modified' => '1',
	  'locked' => '0',
	  'comment' => '2',
	  'comment_default_mode' => '4',
	  'comment_default_order' => '1',
	  'comment_default_per_page' => '50',
	  'comment_controls' => '3',
	  'comment_anonymous' => 0,
	  'comment_subject_field' => '1',
	  'comment_preview' => '1',
	  'comment_form_location' => '0',
	);
	
	$content['verse']  = array (
	  'name' => 'Verse',
	  'type' => 'verse',
	  'description' => 'Quran verse',
	  'title_label' => 'Title',
	  'body_label' => 'Verse',
	  'min_word_count' => '0',
	  'help' => '',
	  'node_options' => 
	  array (
		'status' => true,
		'promote' => true,
		'sticky' => false,
		'revision' => false,
	  ),
	  'old_type' => 'verse',
	  'orig_type' => '',
	  'module' => 'node',
	  'custom' => '1',
	  'modified' => '1',
	  'locked' => '0',
	  'comment' => '2',
	  'comment_default_mode' => '4',
	  'comment_default_order' => '1',
	  'comment_default_per_page' => '50',
	  'comment_controls' => '3',
	  'comment_anonymous' => 0,
	  'comment_subject_field' => '1',
	  'comment_preview' => '1',
	  'comment_form_location' => '0',
	);
	$content['fields']  = array (
	  0 => 
	  array (
		'label' => 'Chapter',
		'field_name' => 'field_chapter',
		'type' => 'nodereference',
		'widget_type' => 'nodereference_select',
		'change' => 'Change basic information',
		'weight' => '1',
		'autocomplete_match' => 'contains',
		'size' => 60,
		'description' => '',
		'default_value' => 
		array (
		  0 => 
		  array (
			'nid' => '',
		  ),
		),
		'default_value_php' => '',
		'default_value_widget' => NULL,
		'required' => 1,
		'multiple' => '0',
		'referenceable_types' => 
		array (
		  'page' => 0,
		  'property' => 0,
		  'story' => 0,
		  'verse' => 0,
		  'file' => 0,
		  'food' => 0,
		  'type' => 'type',
		),
		'advanced_view' => '--',
		'advanced_view_args' => '',
		'op' => 'Save field settings',
		'module' => 'nodereference',
		'widget_module' => 'nodereference',
		'columns' => 
		array (
		  'nid' => 
		  array (
			'type' => 'int',
			'unsigned' => true,
			'not null' => false,
			'index' => true,
		  ),
		),
		'display_settings' => 
		array (
		  'label' => 
		  array (
			'format' => 'above',
			'exclude' => 0,
		  ),
		  'teaser' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  'full' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  4 => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		),
	  ),
	  1 => 
	  array (
		'label' => 'Verse No',
		'field_name' => 'field_verse_no',
		'type' => 'number_decimal',
		'widget_type' => 'number',
		'change' => 'Change basic information',
		'weight' => '2',
		'description' => '',
		'default_value' => 
		array (
		  0 => 
		  array (
			'value' => '',
			'_error_element' => 'default_value_widget][field_verse_no][0][value',
		  ),
		),
		'default_value_php' => '',
		'default_value_widget' => 
		array (
		  'field_verse_no' => 
		  array (
			0 => 
			array (
			  'value' => '',
			  '_error_element' => 'default_value_widget][field_verse_no][0][value',
			),
		  ),
		),
		'required' => 1,
		'multiple' => '0',
		'min' => '',
		'max' => '',
		'precision' => '10',
		'scale' => '0',
		'decimal' => '.',
		'prefix' => '',
		'suffix' => '',
		'allowed_values' => '',
		'allowed_values_php' => '',
		'op' => 'Save field settings',
		'module' => 'number',
		'widget_module' => 'number',
		'columns' => 
		array (
		  'value' => 
		  array (
			'type' => 'numeric',
			'precision' => '10',
			'scale' => '0',
			'not null' => false,
			'sortable' => true,
		  ),
		),
		'display_settings' => 
		array (
		  'label' => 
		  array (
			'format' => 'above',
			'exclude' => 0,
		  ),
		  'teaser' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  'full' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  4 => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		),
	  ),
	  2 => 
	  array (
		'label' => 'Para',
		'field_name' => 'field_para',
		'type' => 'number_decimal',
		'widget_type' => 'number',
		'change' => 'Change basic information',
		'weight' => '3',
		'description' => '',
		'default_value' => 
		array (
		  0 => 
		  array (
			'value' => '',
			'_error_element' => 'default_value_widget][field_para][0][value',
		  ),
		),
		'default_value_php' => '',
		'default_value_widget' => 
		array (
		  'field_para' => 
		  array (
			0 => 
			array (
			  'value' => '',
			  '_error_element' => 'default_value_widget][field_para][0][value',
			),
		  ),
		),
		'required' => 1,
		'multiple' => '0',
		'min' => '',
		'max' => '',
		'precision' => '10',
		'scale' => '0',
		'decimal' => '.',
		'prefix' => '',
		'suffix' => '',
		'allowed_values' => '',
		'allowed_values_php' => '',
		'op' => 'Save field settings',
		'module' => 'number',
		'widget_module' => 'number',
		'columns' => 
		array (
		  'value' => 
		  array (
			'type' => 'numeric',
			'precision' => '10',
			'scale' => '0',
			'not null' => false,
			'sortable' => true,
		  ),
		),
		'display_settings' => 
		array (
		  'label' => 
		  array (
			'format' => 'above',
			'exclude' => 0,
		  ),
		  'teaser' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  'full' => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		  4 => 
		  array (
			'format' => 'default',
			'exclude' => 0,
		  ),
		),
	  ),
	);
	$content['extra']  = array (
	  'title' => '-5',
	  'body_field' => '-2',
	  'revision_information' => '-1',
	  'comment_settings' => '0',
	  'menu' => '-4',
	  'locations' => '-3',
	);

	
	return $content;

}